DoAnChuyenNganh/Controllers/SalePetController.cs
using DoAnChuyenNganh.Models;
using MoMo;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnChuyenNganh.Controllers
{
    public class SalePetController : Controller
    {
        // GET: SalePet
        private List<SanPham> ProductNew(int count)
        {
            return data.SanPhams.OrderByDescending(a => a.NgayCapNhap).Take(count).ToList();
        }

        public ActionResult Index()
        {
            var SPmoi = ProductNew(12);
            return View(SPmoi);
        }
        DataPetBestDataContext data = new DataPetBestDataContext();
        public ActionResult TatCaSanPham(int? page)
        {
            int pagesize = 12;
            int pagenum = (page ?? 1);
            var all = from a in data.SanPhams select a;
            return View(all.ToPagedList(pagenum, pagesize));
        }
        public ActionResult SanPhamTheoDanhMuc(int id, int? page) {
            int pagesize = 12;
            int pagenum = (page ?? 1);
            var theoDM = from sp in data.SanPhams where sp.MaDanhMuc == id select sp;
            return View(theoDM);
        }
        public ActionResult SanPhamTheoLoai(int id, int? page)
        {
            int pagesize = 12;
            int pagenum = (page ?? 1);
            var theoLM = from sp in data.SanPhams where sp.MaLoaiSP == id select sp;
            return View(theoLM.ToPagedList(pagenum, pagesize));
        }
        public ActionResult chitietSP(int id)
        {
            var CTSP = from CT in data.SanPhams where CT.MaSP == id select CT;
            return View(CTSP.Single());
        }
        [HttpPost]
        public ActionResult Search(string keyword, int? page)
        {
            int pagesize = 12;
            int pagenum = (page ?? 1);
            var all = data.SanPhams.Where(x => x.TenSP.Contains(keyword));
            return View(all.ToPagedList(pagenum, pagesize));
        }
        public ActionResult LichSuMH(int id)
        {
            if (Session["tk"] == null)
                return RedirectToAction("LogIn", "NguoiDung");
            else
            {
                var LS = from ls in data.CT_DDHs.OrderByDescending(n => n.MaDDH) where ls.DonDatHang.MaTV == id select ls;
                return View(LS);
            }
        }
        public ActionResult XacNhanDH()
        {
            var SPmoi = ProductNew(12);
            return View(SPmoi);
        }
        public ActionResult PriceFilter(double from, double to, string type, int? page)
        {
            int pagesize = 12;
            int pagenum = (page ?? 1);
            ViewData["from"] = from;
            ViewData["to"] = to;
            if (!String.IsNullOrEmpty(type))
            {
                var all = data.SanPhams.Where(sp => sp.GiaBan >= from && sp.GiaBan <= to && sp.MaLoaiSP == int.Parse(type));
                return View("SanPhamTheoLoai", all.ToPagedList(pagenum, pagesize));
            }
            else
            {
                var all = data.SanPhams.Where(sp => sp.GiaBan >= from && sp.GiaBan <= to);
                return View("TatCaSanPham", all.ToPagedList(pagenum, pagesize));
            }
        }
        
    }
}

DoAnChuyenNganh/Views/SalePet/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPet.cshtml";
}

@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text> . . . </text>
    }
}

<div class="banner">
    <div class="container">
        <section class="rw-wrapper">
            <h1 class="rw-sentence">
            
            </h1>
        </section>
    </div>
</div>


<div class="content">
    <div class="container">
        <!--products-->
        <div class="content-mid">
            <h3 style="text-align:center; font-family: Arial">Sản phẩm mới</h3>
            <label class="line"></label>
            <div class="mid-popular">
                @foreach (var sanphammoi in Model)
                {
                    <div class="col-md-3 item-grid simpleCart_shelfItem">
                        <div class=" mid-pop">
                            <div class="pro-img">
                                <img src="~/Content/images/@sanphammoi.HinhAnh" class="img-responsive" alt="">
                                <div class="zoom-icon ">
                                    <a class="picture" href="~/Content/images/@sanphammoi.HinhAnh" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                    <a href="@Url.Action("chitietSP","SalePet", new { id = sanphammoi.MaSP})"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                </div>
                            </div>
                            <div class="mid-1">
                                <div class="women">
                                    <div class="women-top">
                                        <span>Đồ ăn cho chó</span>
                                        <h6><a href="@Url.Action("chitietSP","SalePet", new { id = sanphammoi.MaSP})">@Truncate(sanphammoi.TenSP, 10)</a></h6>
                                    </div>
                                    <div class="img item_add">
                                        <a href="@Url.Action("Themgiohang","GioHang", new { id = sanphammoi.MaSP, strUrl = Request.Url.ToString() })"><i class="fas fa-shopping-bag" style=" padding: 10px; color: #fff; background-color: #347ab6;"></i></a>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="mid-2">
                                    <p><label>@String.Format("{0:0,0}", sanphammoi.GiaGoc)VND</label><em class="item_price">@String.Format("{0:0,0}", sanphammoi.GiaBan)VND</em></p>
                                    

                                    <div class="clearfix"></div>
                                </div>

                            </div>
                        </div>
                    </div>}

                <div class="clearfix"></div>
            </div>

        </div>
        <!--//products-->
    </div>
</div>

DoAnChuyenNganh/Views/SalePet/LichSuMH.cshtml
@model IEnumerable<DoAnChuyenNganh.Models.CT_DDH>
@{
    ViewBag.Title = "LichSuMH";
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}

<div class="banner-top">
    <div class="container">
        <h1>Single</h1>
        <em></em>
        <h2><a href="index.html">Home</a><label>/</label>Single</h2>
    </div>
</div>

<div class="single">
    <div class="container">
        <table class="table">
            <tr>
                <th>
                    Mã đơn hàng
                </th>
                <th>
                    Ngày mua
                </th>
                <th>
                    Tên Sản phẩm
                </th>
                <th>
                    Hình ảnh
                </th>
                <th>
                    Số lượng
                </th>
                <th>
                    Thành tiền
                </th>
                <th>
                    Trạng thái
                </th>
            </tr>
            @foreach (var item in Model)
            {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.DonDatHang.MaDDH)
    </td>

    <td>
        @String.Format("{0:dd/MM/yyyy}", item.DonDatHang.NgayDat)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.SanPham.TenSP)
    </td>

    <td>
        <img src="~/Content/images/@item.SanPham.HinhAnh" width="100" />
    </td>

    <td style="font-weight:bold">
        @Html.DisplayFor(modelItem => item.SoLuong)
    </td>

    <td>
        @String.Format("{0:0,0}", item.DonGia)
    </td>

    <td style="color:red">
        @Html.DisplayFor(modelItem => item.DonDatHang.TinhTrangGiaoHang1.TinhTrang)
    </td>

</tr>            }
        </table>
    </div>
</div>

DoAnChuyenNganh/Views/SalePet/SanPhamTheoDanhMuc.cshtml
@using DoAnChuyenNganh.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
@{ ViewBag.Title = "SanPhamTheoDanhMuc";
    Layout = "~/Views/Shared/_LayoutPet.cshtml"; }

<div class="content">
    <div class="container">
        <!--products-->
        <div class="content-mid">
            <h3 style="text-align:center; font-family: Arial">Sản phẩm theo danh mục</h3>
            <label class="line"></label>
            <div class="mid-popular">
                @foreach (var SanPhamTheoDanhMuc in Model)
                {
    <div class="col-md-3 item-grid simpleCart_shelfItem">
        <div class=" mid-pop">
            <div class="pro-img">
                <img src="~/Content/images/@SanPhamTheoDanhMuc.HinhAnh" class="img-responsive" alt="">
                <div class="zoom-icon ">
                    <a class="picture" href="~/Content/images/@SanPhamTheoDanhMuc.HinhAnh" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                    <a href="single.html"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                </div>
            </div>
            <div class="mid-1">
                <div class="women">
                    <div class="women-top">
                        <span>Đồ ăn cho chó</span>
                        <h6><a href="single.html">@SanPhamTheoDanhMuc.TenSP</a></h6>
                    </div>
                    <div class="img item_add">
                        <a href="@Url.Action("Themgiohang","GioHang", new { id = SanPhamTheoDanhMuc.MaSP, strUrl = Request.Url.ToString() })"><img src="~/Content/images/ca.png" alt=""></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="mid-2">
                    <p><label>@SanPhamTheoDanhMuc.GiaGoc</label><em class="item_price">@SanPhamTheoDanhMuc.GiaBan</em></p>
                    <div class="block">
                        <div class="starbox small ghosting"> </div>
                    </div>

                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
    </div>}

                <div class="clearfix"></div>
            </div>

        </div>
        <!--//products-->
    </div>

</div>

DoAnChuyenNganh/Views/SalePet/SanPhamTheoLoai.cshtml
@using DoAnChuyenNganh.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
@{ ViewBag.Title = "SanPhamTheoLoai";
                Layout = "~/Views/Shared/_LayoutPet.cshtml"; }

@helper Truncate(string input, int length)
{if (input.Length < length)
                    {
    @input }
                    else
                    {
    @input.Substring(0, length)<text> . . . </text>}
}
@* begin--phân giá *@
<form style="text-align: right; padding-right: 159px" method="get" action="/SalePet/PriceFilter">
    <div class="khoang-gia">Khoảng giá</div>
    <div style="margin-top: -20px">
        <div class="input-gia-cahai">
            <input type="text" min="0" pattern="[0-9]*" maxlength="13" class="input-gia--khung1" placeholder="₫ TỪ" value="" name="from">
            <span class=""></span>
            <input type="text" min="0" pattern="[0-9]*" maxlength="13" class="input-gia--khung1" placeholder="₫ ĐẾN" value="" name="to">
            @if (Model.Count > 0)
            {
<input type="hidden" value="@Model[0].MaLoaiSP" name="type" /> }
else
{


<input type="hidden" value="@Context.Request.QueryString["type"]" name="type" />}
        </div>
    </div>
    <button type="submit" class="btn--apdung">Áp dụng</button>
</form>
@* end--phân giá *@
<div class="content">
    <div class="container">
        <!--products-->
        <div class="content-mid">
            <h3 style="text-align:center; font-family: Arial">Sản phẩm theo loại</h3>
            <label class="line"></label>
            <div class="mid-popular">
                @foreach (var SanPhamTheoLoai in Model)
                {
    <div class="col-md-3 item-grid simpleCart_shelfItem">
        <div class=" mid-pop">
            <div class="pro-img">
                <img src="~/Content/images/@SanPhamTheoLoai.HinhAnh" class="img-responsive" alt="">
                <div class="zoom-icon ">
                    <a class="picture" href="~/Content/images/@SanPhamTheoLoai.HinhAnh" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                    <a href="@Url.Action("chitietSP","SalePet", new { id = SanPhamTheoLoai.MaSP})"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                </div>
            </div>
            <div class="mid-1">
                <div class="women">
                    <div class="women-top">
                        <span>Đồ ăn cho chó</span>
                        <h6><a href="@Url.Action("chitietSP","SalePet", new { id = SanPhamTheoLoai.MaSP})">@Truncate(SanPhamTheoLoai.TenSP, 40)</a></h6>
                    </div>
                    <div class="img item_add">
                        <a href="@Url.Action("Themgiohang","GioHang", new { id = SanPhamTheoLoai.MaSP, strUrl = Request.Url.ToString() })"><img src="~/Content/images/ca.png" alt=""></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="mid-2">
                    <p><label>@String.Format("{0:0,0}", SanPhamTheoLoai.GiaGoc) VND</label><em class="item_price">@String.Format("{0:0,0}", SanPhamTheoLoai.GiaBan) VND</em></p>


                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
    </div>}

                <div class="clearfix"></div>
            </div>

        </div>
        <!--//products-->
    </div>

</div>
<div style="margin: 20px 0; text-align: center">
    <ul>
        @if (ViewData["from"] == "" && ViewData["to"] == "")
        {
            <li class="active"> @Html.PagedListPager(Model, page => Url.Action("SanPhamTheoLoai", new { page = page }))</li>
        }
        else
        {
            if (Model.Count > 0)
            {
                <li class="active">@Html.PagedListPager(Model, page => Url.Action("PriceFilter", new { page = page, from = ViewData["from"], to = ViewData["to"], type = Context.Request.QueryString["type"] }))</li>
            }
        }
    </ul>
</div>

DoAnChuyenNganh/Views/SalePet/Search.cshtml
@using DoAnChuyenNganh.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutPet.cshtml";
}


@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text> . . . </text>
    }
}

<div class="content">
    <div class="container">
        <!--products-->
        <div class="content-mid">
            <h3 style="text-align:center; font-family: Arial">Kết quả tìm kiếm</h3>
            <label class="line"></label>
            <div class="mid-popular">
                @foreach (var KetQuaTimKiem in Model)
                {
                    <div class="col-md-3 item-grid simpleCart_shelfItem">
                        <div class=" mid-pop">
                            <div class="pro-img">
                                <img src="~/Content/images/@KetQuaTimKiem.HinhAnh" class="img-responsive" alt="">
                                <div class="zoom-icon ">
                                    <a class="picture" href="~/Content/images/@KetQuaTimKiem.HinhAnh" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                    <a href="single.html"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                </div>
                            </div>
                            <div class="mid-1">
                                <div class="women">
                                    <div class="women-top">
                                        <span>Đồ ăn cho chó</span>
                                        <h6><a href="single.html">@Truncate(KetQuaTimKiem.TenSP, 40)</a></h6>
                                    </div>
                                    <div class="img item_add">
                                        <a href="#"><img src="~/Content/images/ca.png" alt=""></a>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="mid-2">
                                    <p><label>@String.Format("{0:0,0}", KetQuaTimKiem.GiaGoc) VND</label><em class="item_price">@String.Format("{0:0,0}", KetQuaTimKiem.GiaBan) VND</em></p>


                                    <div class="clearfix"></div>
                                </div>

                            </div>
                        </div>
                    </div>}

                <div class="clearfix"></div>
            </div>

        </div>
        <!--//products-->
    </div>

</div>
<div style="margin: 20px 0; text-align: center">
    <ul>
        <li class="active"> @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiem", new { page = page }))</li>
    </ul>
</div>

DoAnChuyenNganh/Views/SalePet/TatCaSanPham.cshtml
@using DoAnChuyenNganh.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
@{
    ViewBag.Title = "TatCaSanPham";
    Layout = "~/Views/Shared/_LayoutPet.cshtml";
}
@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text> . . . </text>
    }
}
@* begin--phân giá *@
<form style="text-align: right; padding-right: 159px" method="get" action="/SalePet/PriceFilter">
    <div class="khoang-gia">Khoảng giá</div>
    <div style="margin-top: -20px">
        <div class="input-gia-cahai">
            <input type="text" min="0" pattern="[0-9]*" maxlength="13" class="input-gia--khung1" placeholder="₫ TỪ" value="" name="from">
            <span class=""></span>
            <input type="text" min="0" pattern="[0-9]*" maxlength="13" class="input-gia--khung1" placeholder="₫ ĐẾN" value="" name="to">
        </div>
    </div>
    <button type="submit" class="btn--apdung">Áp dụng</button>
</form>
@* end--phân giá *@

<div class="content">
    <div class="container">
        <!--products-->
        <div class="content-mid">
            <h3 style="text-align:center; font-family: Arial">Tất cả sản phẩm</h3>
            <label class="line"></label>
            <div class="mid-popular">
                @foreach (var tatcasanpham in Model)
                {
                    <div class="col-md-3 item-grid simpleCart_shelfItem">
                        <div class=" mid-pop">
                            <div class="pro-img">
                                <img src="~/Content/images/@tatcasanpham.HinhAnh" class="img-responsive" alt="">
                                <div class="zoom-icon ">
                                    <a class="picture" href="~/Content/images/@tatcasanpham.HinhAnh" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                    <a href="@Url.Action("chitietSP","SalePet", new { id = tatcasanpham.MaSP})"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                </div>
                            </div>
                            <div class="mid-1">
                                <div class="women">
                                    <div class="women-top">
                                        <span>Đồ ăn cho chó</span>
                                        <h6><a href="@Url.Action("chitietSP","SalePet", new { id = tatcasanpham.MaSP})">@Truncate(tatcasanpham.TenSP, 10)</a></h6>
                                    </div>
                                    <div class="img item_add">
                                        <a href="@Url.Action("Themgiohang","GioHang", new { id = tatcasanpham.MaSP, strUrl = Request.Url.ToString() })"><img src="~/Content/images/ca.png" alt=""></a>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="mid-2">
                                    <p><label>@String.Format("{0:0,0}", tatcasanpham.GiaGoc) VND</label><em class="item_price">@String.Format("{0:0,0}", tatcasanpham.GiaBan) VND</em></p>


                                    <div class="clearfix"></div>
                                </div>

                            </div>
                        </div>
                    </div>}

                <div class="clearfix"></div>
            </div>

        </div>
        <!--//products-->
    </div>

</div>
<div style="margin: 20px 0; text-align: center">
    <ul>
        @if (ViewData["from"] == "" && ViewData["to"] == "")
        {
            <li class="active">@Html.PagedListPager(Model, page => Url.Action("TatCaSanPham", new { page = page }))</li>

        }
        else
        {
            <li class="active">@Html.PagedListPager(Model, page => Url.Action("PriceFilter", new { page = page, from = ViewData["from"], to = ViewData["to"] }))</li>

        }
    </ul>
</div>

DoAnChuyenNganh/Views/SalePet/XacNhanDH.cshtml
@{
    ViewBag.Title = "XacNhanDH";
    Layout = "~/Views/Shared/_LayoutPet.cshtml";
}

@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text> . . . </text>
    }
}

<div class="banner">
    <div class="container">
        <section class="rw-wrapper">
            <h1 class="rw-sentence">
            </h1>
        </section>
    </div>
</div>


<div class="content">
    <div class="container">
        <!--products-->
        <div class="content-mid">
            <h3 style="text-align:center; font-family: Arial">Sản phẩm mới</h3>
            <label class="line"></label>
            <div class="mid-popular">
                @foreach (var sanphammoi in Model)
                {
                    <div class="col-md-3 item-grid simpleCart_shelfItem">
                        <div class=" mid-pop">
                            <div class="pro-img">
                                <img src="~/Content/images/@sanphammoi.HinhAnh" class="img-responsive" alt="">
                                <div class="zoom-icon ">
                                    <a class="picture" href="~/Content/images/@sanphammoi.HinhAnh" rel="title" class="b-link-stripe b-animate-go  thickbox"><i class="glyphicon glyphicon-search icon "></i></a>
                                    <a href="@Url.Action("chitietSP","SalePet", new { id = sanphammoi.MaSP})"><i class="glyphicon glyphicon-menu-right icon"></i></a>
                                </div>
                            </div>
                            <div class="mid-1">
                                <div class="women">
                                    <div class="women-top">
                                        <span>Đồ ăn cho chó</span>
                                        <h6><a href="@Url.Action("chitietSP","SalePet", new { id = sanphammoi.MaSP})">@Truncate(sanphammoi.TenSP, 10)</a></h6>
                                    </div>
                                    <div class="img item_add">
                                        <a href="@Url.Action("Themgiohang","GioHang", new { id = sanphammoi.MaSP, strUrl = Request.Url.ToString() })"><i class="fas fa-shopping-bag" style=" padding: 10px; color: #fff; background-color: #347ab6;"></i></a>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="mid-2">
                                    <p><label>@String.Format("{0:0,0}", sanphammoi.GiaGoc)VND</label><em class="item_price">@String.Format("{0:0,0}", sanphammoi.GiaBan)VND</em></p>


                                    <div class="clearfix"></div>
                                </div>

                            </div>
                        </div>
                    </div>}

                <div class="clearfix"></div>
            </div>

        </div>
        <!--//products-->
    </div>
</div>
<script>
    alert("Bạn đã đặt hàng thành công")
</script>